2025-01-30 00:31:45,656 - asyncio - DEBUG - Using selector: SelectSelector
2025-01-30 00:31:45,764 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:31:46,115 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:31:56,925 - main - ERROR - Перехвачено исключение внутри get_user_by_id: Internal Server Error
2025-01-30 00:31:56,925 - main - ERROR - Ошибка в get_user_by_id: Internal Server Error
Traceback (most recent call last):
  File "D:\_.programming\unittest_study\lesson1\main.py", line 80, in get_user_by_id
    return await self.__get_user_by_id(user_id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_.programming\unittest_study\lesson1\main.py", line 88, in __get_user_by_id
    result: Result = await self.session.execute(stmt)
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'execute'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\_.programming\unittest_study\lesson1\main.py", line 60, in wrapper
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_.programming\unittest_study\lesson1\main.py", line 84, in get_user_by_id
    raise CustomHTTPException(INTERNAL_SERVER_ERROR, code=status.HTTP_500_INTERNAL_SERVER_ERROR)
main.CustomHTTPException: Internal Server Error
2025-01-30 00:31:59,497 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:32:19,489 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:32:19,854 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:32:25,512 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\main.py')}
2025-01-30 00:32:26,117 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:32:26,535 - asyncio - DEBUG - Using selector: SelectSelector
2025-01-30 00:32:26,627 - watchfiles.main - DEBUG - 6 changes detected: {(<Change.added: 1>, 'D:\\_.programming\\unittest_study\\lesson1\\__pycache__\\main.cpython-312.pyc'), (<Change.deleted: 3>, 'D:\\_.programming\\unittest_study\\lesson1\\__pycache__\\main.cpython-312.pyc.2102775591344'), (<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\__pycache__'), (<Change.added: 1>, 'D:\\_.programming\\unittest_study\\lesson1\\__pycache__\\main.cpython-312.pyc.2102775591344'), (<Change.deleted: 3>, 'D:\\_.programming\\unittest_study\\lesson1\\__pycache__\\main.cpython-312.pyc'), (<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:33:00,544 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
2025-01-30 00:33:00,904 - watchfiles.main - DEBUG - 1 change detected: {(<Change.modified: 2>, 'D:\\_.programming\\unittest_study\\lesson1\\lesson1.log')}
